// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreaturePhenotype } from "./CreaturePhenotype";

export type CreatureAgent = { id: number, speciesId: string, px: number, py: number, vx: number, vy: number, headingAngle: number, bendAngle: number, omegaRot: number, energy: number, adrenaline: number, age: number, generation: number, hasEaten: boolean, genome: string, antisense: string, phenotype: CreaturePhenotype, neuronStates: Array<number>, neuronActivations: Array<number>, };
