// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SensoryPatch = { spectralAffinity: number, bandwidth: number, expressionStyle: number, scale: number, spinalPos: number, angle: number, hueShift: number, geneStartIndex: number, geneEndIndex: number, };
