// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpinalHarmonics = { baseLength: number, meanRadius: number, amplitudes: Array<number>, phases: Array<number>, spinalCurve: number, spinalCurveFreq: number, parapodiaAmp: number, parapodiaFreq: number, flatteningHead: number, };
