// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BiomeArea = { id: string, name: string, x: number, y: number, width: number, height: number, sporeSpawnRate: number, sporeEnergyValue: number, hazardDamage: number, color: string, };
