// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CTRNNNeuron } from "./CTRNNNeuron";
import type { CTRNNSynapse } from "./CTRNNSynapse";

export type BrainTopology = { neurons: Array<CTRNNNeuron>, synapses: Array<CTRNNSynapse>, };
