// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrainTopology } from "./BrainTopology";
import type { HSLColor } from "./HSLColor";
import type { SensoryPatch } from "./SensoryPatch";
import type { SpinalHarmonics } from "./SpinalHarmonics";

export type CreaturePhenotype = { symmetry: string, primaryColor: HSLColor, secondaryColor: HSLColor, bodySeed: number, segments: any[], spinalHarmonics: SpinalHarmonics, emergentChambersCount: number, organelles: Array<SensoryPatch>, pulseSpeed: number, wavePhase: number, wiggleAmplitude: number, stiffness: number, matureAge: number, reproThreshold: number, splitLoss: number, brain: BrainTopology, carnivory: number, isPredator: boolean, latinName: string, sensoryVisus: number, sensoryOlfaction: number, sensoryTactility: number, sensoryBiolum: number, dietClass: string, preferredHabitat: string, basalMetabolicRate: number, stomachCapacity: number, thermalToleranceMin: number, thermalToleranceMax: number, hydraulicPressure: number, rotationalInertia: number, survivalExpectation: number, survivalAnalysis: string, chromatinState: Array<boolean>, epigeneticLogs: Array<string>, methylations: Array<number>, antisenseStrand: string, repairFidelity: number, insertionRate: number, deletionRate: number, genomeString: string, };
