// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NeuronType } from "./NeuronType";

export type CTRNNNeuron = { id: number, type: NeuronType, label: string, tau: number, bias: number, activationType: string | null, x: number | null, y: number | null, };
