// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CurrentVent = { id: number, x: number, y: number, radius: number, forceType: string, strength: number, };
