// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FoodSpore = { id: number, typeId: number, x: number, y: number, amount: number, vx: number, vy: number, };
