// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BiomeArea } from "./BiomeArea";
import type { CurrentVent } from "./CurrentVent";
import type { ProceduralObstacle } from "./ProceduralObstacle";

export type ProceduralWorld = { seed: string, width: number, height: number, obstacles: Array<ProceduralObstacle>, vents: Array<CurrentVent>, biomes: Array<BiomeArea>, };
