// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vertex } from "./Vertex";

export type ProceduralObstacle = { id: number, x: number, y: number, radius: number, type: string, color: string, vertices: Array<Vertex>, };
