// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FoodSpore } from "./FoodSpore";
import type { ProceduralWorld } from "./ProceduralWorld";

export type TrainerTelemetrySandbox = { id: number, px: number, py: number, vx: number, vy: number, heading_angle: number, omega_rot: number, finished: boolean, current_fitness: number, origin_type: string, consumed_spore_type: string | null, foods: Array<FoodSpore>, world: ProceduralWorld, latin_name: string, primary_color_h: number, primary_color_s: number, primary_color_l: number, energy: number, age: number, generation: number, genome: string, };
